# Generated by Django 2.0.7 on 2019-02-05 10:28

from django.db import migrations
from django.contrib.auth.models import Group
from accounts.models import Churches


def create_church_group(apps, schema_editor):

    """
    Create Super admin and churches group
    """

    Group = apps.get_model('auth', 'Group')
    Group.objects.create(name='churches')



class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_church_group),

    ]
